name: Build, Test & Release

on:
  push:

jobs:
  test-test:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      volumes:
        - /cores:/cores
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v2
      - name: "Install build prerequisites"
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -qy gcc procps
      - name: "Enable dumping core files"
        run: |
          ulimit -c unlimited
          sysctl kernel.core_pattern=/cores/core.%P
          chmod a+w /cores
      - name: "Build project"
        run: |
          cc instant_segfault.c -o instant_segfault
          ./instant_segfault
      - name: "Upload core file & binaries as artifacts on test failure"
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-debug-${{ matrix.os }}-${{ github.run_id }}
          path: |
            /cores
            ${{ github.workspace }}/test/db*.log
            ${{ github.workspace }}/test/rts_db
